; Listing generated by Microsoft (R) Optimizing Compiler Version 19.12.25830.2 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\pitte\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
